---
deployment:
  tasks:
    # Clear production directory (keep .htaccess)
    - export DEPLOYPATH=/home1/nvjadcaq/public_html/
    - find $DEPLOYPATH -type f ! -name '.htaccess' ! -name '.well-known' -delete 2>/dev/null || true
    - find $DEPLOYPATH -mindepth 1 -type d ! -name '.well-known' -exec rm -rf {} + 2>/dev/null || true
    # Deploy only production files
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH