---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/nvjadcaq/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH