---
deployment:
  tasks:
    - /bin/rm -rf /home1/nvjadcaq/public_html/*
    - /bin/cp -R * /home1/nvjadcaq/public_html/
    - /bin/chmod -R 644 /home1/nvjadcaq/public_html/*
    - /bin/chmod -R 755 /home1/nvjadcaq/public_html/
    - /bin/find /home1/nvjadcaq/public_html -name "*.html" -exec chmod 644 {} \;